#!/bin/bash

# Ensure a commit message is provided
if [ -z "$1" ]; then
  echo "Usage: push \"commit message\""
  exit 1
fi

# Store the commit message
message="$1"

# Clean and regenerate docs
cargo clean --doc
cargo doc --no-deps --release

# Deploy docs to GitHub Pages
ghp-import -n -p -f target/doc

# Remove all but the most recent maze file in the generated folder, if any exist
generated_dir="./src/game/maze/saved-mazes/generated"
if [ -d "$generated_dir" ]; then
  cd "$generated_dir" || exit
  files=($(ls -tp | grep -v '/$'))
  if [ "${#files[@]}" -gt 1 ]; then
    # Keep the most recent file, remove the rest
    printf "%s\n" "${files[@]:1}" | xargs -d '\n' rm --
  fi
  cd - > /dev/null || exit
fi

# Stage, commit, and push code changes
git add .
git commit -m "$message"
git push -u origin main
